dist: trusty
language: csharp
mono:
  - latest
solution: src/Gir.sln

install:
  - nuget restore src/Gir.sln
  - nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release src/Gir.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./src/Gir.Tests/bin/Release/Gir.Tests.dll

